#!/bin/bash
## Generic namd folder cleanup script                 Mkuiper    April 2010
##
## Danger!! will erase all data in generic namd folder!	
## 

echo    "***"
echo    "***  This script will ERASE ALL DATA in the following folders:"
echo    "***    ../Errors/*"
echo    "***    ../JobLog/*"
echo    "***    ../Outputfiles/*"
echo    "***    ../OutputText/*"
echo    "***    ../RestartFiles/*"
echo    "***    plus all *.coor *.vel *.xsc *.xst *.dcd *.BAK *.old and FFTW* files"
sleep 2
read -p "***    Are you sure? (Y)" YN

case $YN in

  [Y]* )  echo "your wish is my command (line)...";
  cd ../;
  rm -rf OutputText/*; 
  rm -rf OutputFiles/*; 
  rm -rf JobLog/*; 
  rm -rf RestartFiles/*;
  rm -rf Errors/*; 
  rm -f pbs_*.o* pbs_*.e* *.old *.BAK *.vel *.coor *.xsc *.xst FFTW* *.dcd ;;

  [y]*  ) echo  "Phew! Nothing erased! - type uppercase Y to delete!";;
  * ) echo  "Phew! Nothing erased!"  ;;

esac


