#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=0:05:00
#PBS -N AbaqusDoor
#PBS -W x=GRES:abaqus+5
# PBS -m ae

# Go to the directory from which you submitted the job
cd $PBS_O_WORKDIR

module load abaqus
#
# Run the job 'Door'
abaqus job=Door
